<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{{ title }}</title>
</head>

<body>
<!--
| 可用于过滤volt模板中变量
-->
{# comment like this, this statement won't display in html code. #}
{{ tag|e }}
{{ tag }}

{# volt's loop #}
{% for p in loop %}
    <div>{{ p }}</div>
{% endfor %}

{% set numbers = ['one': '1', 'two': 2, 'three': 3] %}
{% for name, value in numbers if value < 2 %}
Name: {{ name }} Value: {{ value }}

Name: {{ name }} Value: {{ value }} >= 2
{% endfor %}

{% do (1+3) %}
{{ 1+3 }}

<form method="post" action="saveArticle">
    <input type="hidden" name="idd" value="">
    <ul>
        <li>title: <input type="text" name="title" value="" maxlength="20"></li>
        <li>content: <input type="text" name="content" value="" maxlength="200"></li>
        <li><input type="submit" value="DO"></li>
    </ul>
</form>

<?php print_r($this->menu); ?>
{{ uri }}
</body>
</html>